package com.example.data

data class GeneratedFile(
    val path: String,
    val category: String,
    val content: String
)

fun generateProjectFiles(
    prompt: String,
    includeRoom: Boolean,
    includeHilt: Boolean,
    includeWorkflows: Boolean,
    includeGemini: Boolean,
    minSdk: String
): List<GeneratedFile> {
    val appSlug = prompt.lowercase().replace(Regex("[^a-z0-9]"), "").take(12).ifEmpty { "myapp" }
    val list = mutableListOf<GeneratedFile>()

    // GitHub-Boss merge: include the offline deterministic Kotlin generator output.
    KotlinCodeMaker.generate(prompt, "com.example").forEach { file ->
        list += GeneratedFile(
            path = "app/src/main/java/com/example/${file.path}",
            category = "Kotlin",
            content = file.content
        )
    }

    list += GeneratedFile(
        path = "app/src/main/java/com/example/MainActivity.kt",
        category = "Android",
        content = """
package com.example

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme {
                Surface(modifier = Modifier.fillMaxSize()) { MainScreen() }
            }
        }
    }
}

@Composable
fun MainScreen() {
    Column(
        modifier = Modifier.fillMaxSize().padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Text("Generated App: $prompt", style = MaterialTheme.typography.titleMedium)
        Spacer(modifier = Modifier.height(16.dp))
        Button(onClick = {}) { Text("Interactive Action") }
    }
}
""".trimIndent()
    )

    list += GeneratedFile(
        path = "app/build.gradle.kts",
        category = "Android",
        content = """
plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    ${if (includeHilt) "id(\"com.google.dagger.hilt.android\")" else ""}
    ${if (includeRoom) "alias(libs.plugins.google.devtools.ksp)" else ""}
}

android {
    namespace = "com.example"
    compileSdk = 36
    defaultConfig {
        applicationId = "com.aistudio.$appSlug.app"
        minSdk = $minSdk
        targetSdk = 36
        versionCode = 1
        versionName = "1.0.0"
    }
    buildFeatures { compose = true; buildConfig = true }
}

dependencies {
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.activity.compose)
    ${if (includeRoom) "implementation(libs.androidx.room.runtime)\n    implementation(libs.androidx.room.ktx)" else ""}
    ${if (includeGemini) "implementation(libs.firebase.ai)" else ""}
}
""".trimIndent()
    )

    list += GeneratedFile(
        path = "app/src/main/AndroidManifest.xml",
        category = "Android",
        content = """
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.MyApplication">
        <activity android:name=".MainActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
""".trimIndent()
    )

    if (includeWorkflows) {
        list += GeneratedFile(
            path = ".github/workflows/build-android.yml",
            category = "Workflow",
            content = """
name: Build & Test Android
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
      - name: Build Debug APK
        run: gradle assembleDebug --no-daemon
      - name: Run Unit Tests
        run: gradle testDebugUnitTest --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
""".trimIndent()
        )
    }

    list += GeneratedFile(
        path = "README.md",
        category = "Docs",
        content = """
# $prompt

Generated by the merged Git2- + GitHub-Boss builder.

Features:
- Jetpack Compose + Material 3
- ViewModel + StateFlow
- Offline deterministic Kotlin generation
- Optional Gemini code generation service
- ${if (includeRoom) "Room database stubs" else "In-memory state"}
- ${if (includeWorkflows) "GitHub Actions CI" else "No workflow"}
""".trimIndent()
    )

    return list
}
